### ISSUE TITLE
Multiple Messages.

### ISSUE THREAD

**Issue by AlexanderQueen** [Huguitis/AutoSendDiscordMessage#1]
How to send multiple messages with different delay?

**Comment by Huguitis** [comment]
All the way down: 
```sleep (here delay in seconds)```

**Comment by AlexanderQueen** [comment]
Nah. That won't work. I figured out how. But, in rest i like your idea with token, it impressive.

**Comment by Huguitis** [comment]
Yes that works for me, the sleep function is the delay between each message, and thx <3
